### PR TITLE
Add borders to RU themed screenshots

### PR DESCRIPTION
**Pull request by stijndelaat**
This branch is to replace all the new RU themed screenshots with a version with borders.

@jesask and @miriamkos: I don't think these updated screenshots are usable for the Donders site, seeing that these are the images with the RU logo. However, I have added you, because you can have a look at what they look like and decide if you would like your images to have borders too. Although this would cost me quite some time.

@paulspeijers If you prefer smaller commits I can offer the following aggregation:
Update screenshots on…
Commit 3810c1a t/m aa1804d -> … subpages of get-started
Commit db51a4b –t/m 4d3f4b7 -> … subpages of transfer-data (i.e. check-transferred-data, cyberduck and data-access-account)
Commit 2db2a4f t/m 42daeda -> …subpages of archive-publish-collection
Commit 64531f7 t/m 874b6de -> …subpages of access-shared-data 
Commit a40bd2a t/m da6cda1 -> …faq-publish-data page

Best,

Stijn

### CODE REVIEW

**Comment by miriamkos** [comment]
@paulspeijers ik zou deze aanpassing graag willen zien. Waar kan dit?

**Comment by paulspeijers** [comment]
Hi @miriamkos, https://data-acc.ru.nl would be the place. 

@stijndelaat By the way, I'm no UI expert, but I would personally like it better when the borders would be as thin as possible. Now they're quite big.

**Comment by stijndelaat** [comment]
@miriamkos Hoi Miriam, ze zijn nu zichtbaar op de acceptatie omgeving van de rdr (https://data-acc.ru.nl/doc/help/user-manual.html). En dan met name op de pagina's onder user manual en die ene faq pagina. Wil je een lijst voor de specifieke pagina's?

**Comment by paulspeijers** [comment]
@stijndelaat The beauty of Git is that you can see exactly what has changed within this pull request.

**Comment by stijndelaat** [comment]
@paulspeijers Nice. I am looking forward to the course on Git that you suggested :)

**Comment by miriamkos** [comment]
Dat ziet er inderdaad mooi uit. De dunne randen vinden we het mooist. Omdat we willen proberen onze omgevingen meteen zo gelijk mogelijk willen houden, zouden we dit ook graag willen hebben. Ondanks dat we wel begrijpen dat dit werk voor jou @stijndelaat met zich meebrengt.

**Comment by paulspeijers** [comment]
Hi @stijndelaat,

I now added some styling to the web portal to add borders to each image within the help page. The changes have been deployed on acceptance. You can view some examples here:
https://data-acc.ru.nl/doc/help/user-manual/transfer-data/data-access-account.html

For some pictures now the style is not that pretty, because the screenshot has been created with a white border around it. I would suggest checking all screenshots whether it looks ok, and if not uploading new screenshots. For instance:
https://data-acc.ru.nl/doc/help/user-manual/transfer-data/YodaDrive.html

Did you know that you can make a screenshot of just a selected window using alt + Print screen?
This would also make the following screenshot a little prettier that now has some dark spots around the edges:

https://data-acc.ru.nl/doc/help/user-manual/transfer-data/data-access-account.html

Please let me know whether this is ok and how to proceed.

**Comment by stijndelaat** [comment]
The borders are added in the webportal itself by Paul.

**Pull request closed without merging**
