### PR TITLE
update yodadrive - added step 5

### PR DESCRIPTION
**Pull request by stijndelaat**
Added step 5 on how researchers can add files to the Yoda Drive folder.

### CODE REVIEW

**Comment by miriamkos** [comment]
Seems like a valuable addition to me. One stupid question though, still learning this system and you probably explained this to me before: Where can I actually see the change? I checked https://data-acc.ru.nl/doc/help/user-manual/transfer-data/YodaDrive.html?3&highlight=yoda, but there I only see 4 steps.

**Comment by stijndelaat** [comment]
@miriamkos Good question. You can kinda see what it looks like here: https://github.com/Radboud-University/rdr-configurable-content/blob/rdr-YodadriveManual-update/doc/help/user-manual/transfer-data/YodaDrive.rst. Even though this is not the real website. Perhaps Paul can give you a better answer.

**Comment by miriamkos** [comment]
Thanks Stijn. I think this is a good addition and we would also like to have it on the help of the DR.

**Comment by miriamkos** [comment]
hmmm I hit the close button, but probably that was the wrong one here....sorry

**Comment by stijndelaat** [comment]
@miriamkos @jesask and @paulspeijers I have tweaked the sentence slightly. Are you still in agreement?

It now says: 

> 5. You can now add files to your Yoda Network folder via Windows Explorer and they will appear in your RDR collection.

**Pull request merged**
