### PR TITLE
RDR-3521 Improve file download instruction

### PR DESCRIPTION
**Pull request by paulspeijers**

### CODE REVIEW

**Review by hurngchunlee — CHANGES_REQUESTED** [review]
@paulspeijers The URL for the documentation is hardcoded ... shouldn't it be using a variable?

**Comment by paulspeijers** [comment]
Good one @hurngchunlee. Missed it. Applied a variable.

**Review by hurngchunlee — APPROVED** [review]
Thanks @paulspeijers.  It looks good to me.

**Review by stijndelaat — APPROVED** [review]
Looks fine to me

**Comment by paulspeijers** [comment]
Merged to rdr-release. @hurngchunlee  could you cherry-pick it?

**Comment by hurngchunlee** [comment]
@paulspeijers I have cherry-picked to the dr-acceptance.

**Comment by miriamkos** [comment]
Thanks all for taking care of this. Looks good.

**Pull request merged**
