### PR TITLE
Transfer data checkmarks

### PR DESCRIPTION
**Pull request by stijndelaat**
I have replaced the X symbol in the table on the transfer data page with a check image.

There was some trial and error involved, so some commits are not usefull anymore. However it all serves the purpose described above, so @paulspeijers you can combine them all into one commit that says something like "added checkmarks to table transfer data"

### CODE REVIEW

**Comment by jesask** [comment]
HI Stijn, I agree with your edits, but I'm not sure how I should respond; can I merge pull request and then confirm pull request without accepting previous edits yet?

**Comment by stijndelaat** [comment]
Hi Jessica, I am not sure how you should respond. @paulspeijers will know this. Thanks for your comment!

**Comment by paulspeijers** [comment]
Hi @jesask and @stijndelaat. No! Jessica should not merge this pull request because merging a pull request effectively makes 2 branches the same. This implies all changes for the RDR will be transferred to DR as well.

Instead a system administrator (such as me or Hong) can in Git terms cherry-pick the required commits and add then to DR instead.

**Comment by jesask** [comment]
HI @paulspeijers ok, and we also agreed that it's sufficient for us, if one of us approves, so don't wait for the second reviewer!. Are the adjustments visible somewhere? Because now we cannot really check the changes, although I understand what @stijndelaat means.

**Comment by hurngchunlee** [comment]
> So it's sufficient when you just say you want these changes. Then a system administrator (such as me or Hong) can in Git terms cherry-pick the required commits and add then to DR instead.

@paulspeijers are you sure cherry-picking is doable and safe?  I am not so keen on doing cherry-picking, because it requires clean commits.

**Comment by paulspeijers** [comment]
@hurngchunlee  usually you can see within the commit whether it's safe but what's the alternative, replaying commits on another branch by hand?

**Comment by hurngchunlee** [comment]
@paulspeijers we are running into something I worried about ... since we didn't draw a line between common part and instance-specific part of the configurable content.

In an ideal workflow, I would suggest the editor working on a instance-specific part (in DR or RDR specific branches) should file a pull request to the branch where the common part is maintained (e.g. the master branch) when the editor thinks the changes made is generic and beneficial to other instances.  Once the changes are accepted and merged into the common part, editors from other instances can then safely pull it to their own branches.

Currently if a commit contains more than what it says, cherry-picking or replay will very likely add unwanted content which then require the editor to review and clean/fix it ==> this is why I said cherry-picking requires "clean commits".

**Comment by hurngchunlee** [comment]
For this pull request, I think cherry-picking should still work given the included commits are pretty self-contained.  I can give it a try and let Jessica review the result of cherry-picking. ok?

**Comment by paulspeijers** [comment]
Ok sure.

I agree it could be error prone. I would say it's the responsibility of the commiter to create clean commits, and the responsibility of the content manager to review them to be clean.

**Comment by hurngchunlee** [comment]
> HI @paulspeijers ok, and we also agreed that it's sufficient for us, if one of us approves, so don't wait for the second reviewer!. Are the adjustments visible somewhere? Because now we cannot really check the changes, although I understand what @stijndelaat means.

@jesask I have cherry-picked the changes to dr-acceptance.  On top of that I also made few changes concerning reST syntax.  You can review it on the data-acc portal.

**Comment by jesask** [comment]
Hi @hurngchunlee I reviewed the updates on the data-acc.donders portal and it all looks fine to me, so you can publish it. Only update required, is one screenshot (about YodaDrive), which I have created (but not updated). What is the general process now, should I first update this screenshot now before you publish the updates, or?

**Comment by hurngchunlee** [comment]
> Hi @hurngchunlee I reviewed the updates on the data-acc.donders portal and it all looks fine to me, so you can publish it. Only update required, is one screenshot (about YodaDrive), which I have created (but not updated). What is the general process now, should I first update this screenshot now before you publish the updates, or?

@jesask you could update to the dr-acceptance branch.  After you push it, wait for a while then you should see the update on the DR acceptance.

**Comment by jesask** [comment]
@hurngchunlee, I've added and updated the image; can you publish it? Thanks

**Comment by stijndelaat** [comment]
@paulspeijers Now that this request has been approved, is it also possible to change this on the RDR production environment? Do I need to do something for that?

**Pull request merged**
