### PR TITLE
Added ethical review boards

### PR DESCRIPTION
**Pull request by stijndelaat**
As requested by Didi and Inge, I have added "EACLM", "REC" and "EC RTA" to the popular list.

### CODE REVIEW

**Comment by stijndelaat** [comment]
@paulspeijers and/or @ramonvansparrentak Am I free to add the Donders Crew?

**Comment by stijndelaat** [comment]
@paulspeijers and/or @ramonvansparrentak Do I have your ok to add the Donders Crew?

**Comment by stijndelaat** [comment]
@paulspeijers and/or @ramonvansparrentak Friendly reminder that this request is still here.

**Review by ramonvansparrentak — APPROVED** [review]

**Comment by stijndelaat** [comment]
I have added the Donders Crew 😄 
@miriamkos Would you like this change to the DR as well?

**Comment by miriamkos** [comment]
Yes I am ok with added review boards, and adding the Donders crew;)

**Review by hurngchunlee — APPROVED** [review]
ok with me.  I am cherry-picking to dr-acceptance.

**Comment by hurngchunlee** [comment]
changes have been cherry-picked to dr-acceptance and dr-production branches.

**Pull request merged**
