### PR TITLE
Update instruction archive error message

### PR DESCRIPTION
**Pull request by stijndelaat**
Removed the ethical aproval required example and screenshot on https://data-acc.ru.nl/doc/help/user-manual/archive-publish-collections/archive-dac-rdc.html

Jira issue: [RDR-3406](https://radboud.atlassian.net/browse/RDR-3406)

### CODE REVIEW

**Comment by miriamkos** [comment]
Ok, we would also like to have this change.

**Comment by stijndelaat** [comment]
@paulspeijers Shall I include Hong in this and other branches as assignee? That way he can merge the branches with DR.

**Comment by hurngchunlee** [comment]
@stijndelaat yes, you could assign such kind of request to me in the future.  I will cherry pick this commit to the DR branch.

**Comment by hurngchunlee** [comment]
@miriamkos I have merged the change to the `dr-acceptance`.  Could you please check the DR acceptance website https://data-acc.donders.ru.nl/doc/help ? Let me know if I should proceed to push it to the DR production.

**Comment by stijndelaat** [comment]
@paulspeijers Is it ok for me to merge this branch with rdr-acceptance, since Hong has merged it with dr-acceptance? And remove this pull request afterwards?

**Comment by hurngchunlee** [comment]
> @paulspeijers Is it ok for me to merge this branch with rdr-acceptance, since Hong has merged it with dr-acceptance? And remove this pull request afterwards?

@stijndelaat the right procedure is that you first merge the pull request https://github.com/Radboud-University/rdr-configurable-content/pull/110.  After that, my fix will automatically be added to this pull request.

**Comment by stijndelaat** [comment]
@hurngchunlee Thanks for the fix!

I asked, because we have not decided if I am allowed to just merge branches without an 'ok' from @paulspeijers. For now, we agreed that after you (Hong) have merged branches with dr, I will ask Paul for the greenlight before I merge into rdr.

**Comment by miriamkos** [comment]
> 
> 
> @miriamkos I have merged the change to the `dr-acceptance`. Could you please check the DR acceptance website https://data-acc.donders.ru.nl/doc/help ? Let me know if I should proceed to push it to the DR production.

Yes I checked it and it is ok to push it to production

**Comment by paulspeijers** [comment]
Hi @stijndelaat did you see my comment about removing the png file?

**Comment by stijndelaat** [comment]
> 
> 
> Hi @stijndelaat did you see my comment about removing the png file?

Hi, no I had missed that one. I have replied in that commit.

**Pull request merged**
