### PR TITLE
3508 - YodaDrive and save button

### PR DESCRIPTION
**Pull request by stijndelaat**
I have made a pull-request for Jira issue 3508 (https://radboud.atlassian.net/browse/RDR-3508)

This includes:
- Update of YodaDrive manual to include new collection identifier
- Update of Quickstart -> save changes button

**Not to be merged untill the release of 5.4.0**

### CODE REVIEW

**Comment by stijndelaat** [comment]
@paulspeijers and/or @ramonvansparrentak  I have changed the image 'Yoda_collection_identifier.png' in this branch, however, it still shows the old version of this image in the acceptance environment. I guess it has to do with the call `.. figure:: etc` that has not been changed. Only the image under the filename has been changed. Will this work once we merge? If no, is there a way to make it work in this branch?

**Comment by ramonvansparrentak** [comment]
> it still shows the old version of this image in the acceptance environment.

Glitch in the matrix. Working fine now!

**Comment by stijndelaat** [comment]
@paulspeijers We need to ask Donders if they want this change as well. I don't know when we need to do this, now that this branch is deleted. Can you help me?

**Comment by paulspeijers** [comment]
Merged it to dr-acceptance: https://github.com/Radboud-University/rdr-configurable-content/commits/dr-acceptance

**Comment by stijndelaat** [comment]
@miriamkos and @hurngchunlee Would you like this change as well? As you can see it is part of a larger release.

**Comment by miriamkos** [comment]
Yes, we would like to have these changes as well. I asked Pauline (my colleague) to create the DR-specific pictures of the Yoda manual.

**Comment by hurngchunlee** [comment]
I have cherry-picked it to the dr-acceptance. @miriamkos you could check it on data-acc.donders.ru.nl

**Comment by miriamkos** [comment]
Thanks @hurngchunlee I see the adjustments for Yodadrive. However, text in quickguide step 3 point 5 still differs from the ru-acc environment, this should be update collection instead of save changes, like the ru-acc environment.

**Comment by hurngchunlee** [comment]
@miriamkos I updated the Yodadrive picture from Pauline.  About the quickstart, I don't know where the difference comes.  I did a compare with rdr-release and manually update the text in the dr branch.

You can check again on data-acc.donders.ru.nl.  If you agree, I will push to the production of DR.

**Comment by miriamkos** [comment]
Yes, the adjustments are fine. I am sorry I notice another thing that I missed before, underneath step2 the Donders info needs to be inserted. I thought I shared this info before, but I will email it to you

**Comment by hurngchunlee** [comment]
@miriamkos I am aware of it.  I am waiting for update from @stijndelaat on your comment in https://github.com/Radboud-University/rdr-configurable-content/pull/128; or you directly update on the dr-acceptance branch as the content editor.

**Comment by stijndelaat** [comment]
> 
> 
> @miriamkos I am aware of it. I am waiting for update from @stijndelaat on your comment in #128; or you directly update on the dr-acceptance branch as the content editor.

@hurngchunlee. @miriamkos and I have decided that point two under the quickstart guide will be tailored to the DR specific. I have e-mailed Miriam the correct text that could be inserted there. Is that the update you required? If not, just let me know :)

**Pull request merged**
