### PR TITLE
Rdr quick fixes

### PR DESCRIPTION
**Pull request by stijndelaat**
I have added the following quick fixes:
- https://radboud.atlassian.net/browse/RDR-3455: Homepage change. New text
- https://radboud.atlassian.net/browse/RDR-3456: Quick Start page. I have added the new quick start page
- https://radboud.atlassian.net/browse/RDR-3457: YodaDrive instruction update. I have added some additional steps.

These required some extra changes on other pages:
- I have changed the table of content to include our quick fixes.
- I have renamed rdm-nutshell in glossary (more edits to come)
- I have changed "login to portal" to "login"
- I have changed "Get started" in "Setting up" in the toc.srt file
- Changed the title of 'get started' page to the 'setting up' page.
- Made some textual changes and added link to the Quick start guide to the get-started/setting up page.
- Changed 'login in portal' to 'login' in toctree on the get-started/setting up page
- Changed 'get started' in 'setting up' in the toctree on user-manual.rst

### CODE REVIEW

**Comment by stijndelaat** [comment]
@DidiLamers Would you mind checking if I missed something? It should be visible on the acceptance environment. Please do not merge yet!

@paulspeijers and @ramonvansparrentak I have added you to this pull request, because I would like some help with 2 issues that I was unable to resolve:

1. We wanted to replace the 'home' of the help pages by our new quick start guide. However, the old home was situated in the index.rst file and when I changed this file, I just got errors on the help page. To avoid this, in stead of editing this file, I created a new page 'quickstart.rst'. However, When you push the 'help' button on the top right of the screen, you are still directed to the old index page. How can we change this?
2. I wanted to include 2 buttons on the homepage (the RDR homepage, not the help homepage; data-acc.ru.nl). I have tried around 6 times to include these buttons, but failed to make it work. You do see the 'alt' text, so the code works on some level. Could one of you help me with this?

Thank you in advance!

**Comment by DidiLamers** [comment]
@stijndelaat the changes are not yet visible on the acceptance environment (at least for me). Is that possible?

**Comment by stijndelaat** [comment]
@DidiLamers Yea, I just realised that I had overwritten this with the content-flow-branch.
@paulspeijers and/or @ramonvansparrentak is it possible to make this branch visible in acceptance again?

**Comment by ramonvansparrentak** [comment]
> is it possible to make this branch visible in acceptance again?

Yes, make some changes and commit 😉  (For example to the README.md)

**Comment by ramonvansparrentak** [comment]
> However, When you push the 'help' button on the top right of the screen, you are still directed to the old index page. How can we change this?

@stijndelaat You can change the help url by changing the value of  `"navbar.helpButton"` in the external_urls.json file:

https://github.com/Radboud-University/rdr-configurable-content/blob/0a1f5bfe7dfbfcb58ce0eb0d169d0dddcbcb3be5/external_urls.json#L53

For example
`"navbar.helpButton" : "/doc/help/faq.html",` will make the button go to the FAQ. 

But I think that a "Quick start" button next to the Help button. Or a quick start link in the help index, is preferable..

>  I just got errors on the help page.

What kind of errors?

> so the code works on some level. Could one of you help me with this?

Yes sure, I have no clue how to do this, but I think we can figure it out 🤓  Can you show me what you've tried and what failed? Share your screen on zoom?

**Comment by stijndelaat** [comment]
@ramonvansparrentak Thanks! I have solved question 1

**Review by DidiLamers — CHANGES_REQUESTED** [review]
@stijndelaat thanks! Er zijn nog een paar kleine dingetjes:
1) de quick-start guide en de data access knoppen verschijnen niet als knoppen maar gewoon als linkjes op de homepage
2) de link naar de CLS en RICH specifieke hulppagina om een collectie aan te vragen doet het niet bij mij (ik krijg een melding "pagina niet gevonden. Het spijt ons; de door u opgevraagde pagina bestaat niet (meer)." Wellicht dat ik gewoon niet op het intranet van letteren mag, maar ik denk dat ik daar gewoon bij zou moeten kunnen. Check het in ieder geval nog even.
3) in step 3 van de quick start guide staat "more information can be found here" maar de link ontbreekt

**Comment by stijndelaat** [comment]
@DidiLamers Bedankt voor de feedback!
1. Hier wordt aan gewerkt. Het lukte mij niet alleen.
2. Dit is nu veranderd. Letteren had de link aangepast waardoor de oude link niet meer werkte. Wellicht iets om mee te geven aan de instituten dat wanneer ze de aanvraag link veranderen, dat ze ons ook een seintje geven.
3. Goed gezien! Aangepast.

**Comment by DidiLamers** [comment]
@stijndelaat top, dan is het wat mij betreft helemaal in orde zodra de knoppen gefixt zijn :)

Goed punt om mee te geven aan instituten ons op de hoogte te houden als de links veranderen. Staat genoteerd.

**Comment by stijndelaat** [comment]
@DidiLamers The buttons work! I will merge this branch with acceptance. Do we want to push it directly to production or do we need to wait for something?

**Comment by DidiLamers** [comment]
@stijndelaat great! The buttons are a bit large I think. Can we make them somewhat smaller?

**Comment by stijndelaat** [comment]
@miriamkos We have made some changes on the RDR site. See the top comment for exactly what is changed.

Do you want (some of) these changes for the DR as well?

**Pull request merged**
