### PR TITLE
Rdr quick fixes additions

### PR DESCRIPTION
**Pull request by stijndelaat**
Second try in same branch. Images needed scaling.

### CODE REVIEW

**Comment by stijndelaat** [comment]
@DidiLamers vind je dit een mooi formaat? Nu is het zichtbaar in acc

**Review by DidiLamers — APPROVED** [review]
Nice, @stijndelaat it looks great!

**Comment by stijndelaat** [comment]
@miriamkos If you agree with the previous pullrequest on quick fixes, you might want this one as well. I have just made the buttons on the homepage a bit smaller.

**Comment by miriamkos** [comment]
> 
> 
> @miriamkos If you agree with the previous pullrequest on quick fixes, you might want this one as well. I have just made the buttons on the homepage a bit smaller.

Yes fine, we also would like to have this change!

**Comment by stijndelaat** [comment]
@miriamkos Thank you! Does this mean that you would like all the changes in pull request https://github.com/Radboud-University/rdr-configurable-content/pull/121 as well?

@hurngchunlee If so, would you like to merge both these pull requests to dr?

**Comment by hurngchunlee** [comment]
@stijndelaat is it just about these two commits in this pull request?  I don't think so because we also need to add the two new button images to `dr-acceptance`, right?  Further, there is also a new quick guide page that is full of RDR-specific information that is not suitable for DR instance. e.g. https://data-acc.ru.nl/doc/help/quickstart.html

@miriamkos are you sure we need this?

**Comment by stijndelaat** [comment]
@hurngchunlee Yes, this specific pull request is about the size of the two buttons. I made a new pull request, because I had already merged pull request #121 with acceptance and did not know how to do this easier. So basically, this is an improvement on #121.

**Comment by hurngchunlee** [comment]
Thanks @stijndelaat for the original pull request.

@miriamkos I have included changes (by either `git cherry-pick` or `git checkout`) from the two pull requests:

- https://github.com/Radboud-University/rdr-configurable-content/pull/121
- https://github.com/Radboud-University/rdr-configurable-content/pull/122

The result is deployed to https://data-acc.donders.ru.nl

I think you need to have a look of several pages as they contain RDR specific information to be adjusted for DR.  From what I can see, the following pages are starting points:

- https://data-acc.ru.nl/doc/help/quickstart.html
- https://data-acc.ru.nl/doc/help/user-manual/transfer-data/YodaDrive.html

**Comment by miriamkos** [comment]
Thanks for pointing this out @hurngchunlee, I thought it only concerned a lay-out issue, but indeed point 2 of the quickstart does not include DI. In order to be future-proof when DR becomes RDR, best way would be to already include DI in the RDR documentation right? @stijndelaat, do you agree with this ...we can provide you with the details? We will also look into the yoda drive page.

**Comment by miriamkos** [comment]
DR-specific pictures have been send to Hong.

ALso, the text mentions several times RDR instead of DR. Is it possible to solve this with a variable, just like we did with the urls? @stijndelaat @hurngchunlee

**Comment by stijndelaat** [comment]
@miriamkos Yes, I think I can fix that, depending on the answer to my question below to the developers. 

I will make a new branch in which I will replace alle mentions of the RDR with a variable. This concerns the quickstart (https://data-acc.donders.ru.nl/doc/help/quickstart.html) and the Yodadrive (https://data-acc.donders.ru.nl/doc/help/user-manual/transfer-data/YodaDrive.html) page right?

@paulspeijers, @ramonvansparrentak and @hurngchunlee Is it possible to add a variable that works similar to the variable `repositoryDescription`, but with an abbreviation. In other words: `RDR` for the in the RDR and `DR` for in the DR? Otherwise, everytime we mention an RDR collection it is typed as 'Radboud Data Repository collection'. Wich is ok for once, but starts to annoy me when we do this several times on one page.

**Comment by miriamkos** [comment]
Sounds good. Yes we have seen this in the pages you mention...but probably it occurs more often on other pages.

**Comment by stijndelaat** [comment]
@miriamkos I'll have a look on our own help pages and before I start making edits I will e-mail you a list with pages on which I have seen them. In order for you to approve them/check them on the DR. Does that seem like a good idea?

**Comment by hurngchunlee** [comment]
@stijndelaat I have cherry-picked the changes to dr-acceptance.

I also fixed a rst syntax issue after you applied the variable in a section header.  It is the commit https://github.com/Radboud-University/rdr-configurable-content/commit/dd40dfb214110861c79289fadfab1b7449ead06c You might want to cherry-pick it.

**Comment by stijndelaat** [comment]
> I also fixed a rst syntax issue after you applied the variable in a section header. It is the commit [dd40dfb](https://github.com/Radboud-University/rdr-configurable-content/commit/dd40dfb214110861c79289fadfab1b7449ead06c) You might want to cherry-pick it.

@paulspeijers and/or @ramonvansparrentak Could one of you cherry-pick this commit to the RDR? I don't know how to do this (yet).

**Comment by paulspeijers** [comment]
Thanks I just applied Hong's fix on rdr-acceptance

**Pull request merged**
