### PR TITLE
added repository and institutional variables where applicable for RDR acceptance

### PR DESCRIPTION
**Pull request by robertoostenveld**
${repositoryName} = RDR / DR
${repositoryDescription} = Radboud Data Repository / Donders Repository
${organizationName} = RU / DI
${organizationDescription} = Radboud University / Donders Institute

### CODE REVIEW

**Comment by robertoostenveld** [comment]
In general I have tried to avoid the abbreviations DI and RU.

There were some issues that I identified but did not fix:

- internal documentation points to intranet, which is either https://www.radboudnet.nl/ or https://intranet.donders.ru.nl
- URLs in general are not correct/consistent, for example http://data-acc.ru.nl should be https://data.ru.nl (with an S, and without the ACC). But also https://data.donders.ru.nl 
- SfN keywords are not appropriate outside the DI.
- The FAQ on organizing data collections and "Where should I store personal information about the participants?" has a DI specific answer that might not apply to other OUs.
- The term PI might not apply elsewhere in the RU

**Comment by robertoostenveld** [comment]
Where the reference to a policy within the DI actually points to something at the RU level, e.g., the "password policy" or the "security officer", I kept it as "Radboud University".

**Comment by robertoostenveld** [comment]
@paulspeijers please note that `repositoryUrl` should be data.donders.ru.nl without `https://`  and without trailing '/'. There are some places where something is pasted directly in front or after the variable.

**Comment by robertoostenveld** [comment]
@paulspeijers wrote

> ik heb de volgende variabelen toegevoegd.
>  
> repositoryWebdavUrl à https://webdav.data.donders.ru.nl:443 / https://webdav.data. ru.nl:443 (maar ik vermoed dat default poort 443 ook weg kan uit de configuratie).
> repositoryWebdavPublicUrl à https://public.data.donders.ru.nl:443 / https://public.data.ru.nl:443
> repositorySupportEmail à datasupport@donders.ru.nl of rdmsupport@ubn.ru.nl

and I will update this branch accordingly

**Comment by robertoostenveld** [comment]
Oh paul, we also need something for `https://public.${repositoryUrl}`

**Comment by paulspeijers** [comment]
Hi Robert,

Can you call me about this? 0647326384

I have until 11, no pressure 😊

Met vriendelijke groet / kind regards,

Paul Speijers | Senior software engineer | IT service centrum | Radboud Universiteit | Postbus 9102, 6500 HC Nijmegen | (024) 361 78 38 |www.ru.nl<http://www.ru.nl/>

Aangepaste Corona werkuren: ma en do volledig, di en vr ochtend en wo middag

**Comment by robertoostenveld** [comment]
@paulspeijers this is now ready to be merged with the master (also known as the "rdr-acceptance") branch.

I will make a separate PR with the same changes for the dr (also known as "dr-acceptance") branch

**Pull request merged**
