### PR TITLE
Correct link on homepage

### PR DESCRIPTION
**Pull request by stijndelaat**
The link under data steward was dead. Fixed it.

Please also push to the production environment.

### CODE REVIEW

**Comment by jesask** [comment]
thanks, we would like this update as well

**Comment by hurngchunlee** [comment]
@jesask I have picked it; but then noticed it is actually changing the link of data-steward to the RU link instead of the DR specific data-steward page.  For instance, this commit uses

 http://www.ru.nl/rdm/vm/policy-documents/

instead of

https://www.ru.nl/donders/research/research-data-management/

Do you really want it?

**Comment by jesask** [comment]
yes, I saw it, I think it's fine, it will lead to the data stewards name and the policy document

**Comment by hurngchunlee** [comment]
> yes, I saw it, I think it's fine, it will lead to the data stewards name and the policy document

ok, publishing to production on the way.

**Pull request merged**
