### PR TITLE
QS-update Law

### PR DESCRIPTION
**Pull request by stijndelaat**
I have added the e-mails of the datasteward and policy advisor research of the faculty of Law under step 2 of the Quickstart manual.

### CODE REVIEW

**Comment by stijndelaat** [comment]
@miriamkos I don't know if you have the quick start guide on the DR currently, but if you do, this is an updated version.

**Comment by miriamkos** [comment]
> 
> 
> @miriamkos I don't know if you have the quick start guide on the DR currently, but if you do, this is an updated version.

@stijndelaat @hurngchunlee it would be great to have this guide as well. In step 2 it will be necessary to include the DI information as well. Would it be an idea to already put this info in the RDR info, as in the end we would also need it in there when we join RDR?

**Comment by hurngchunlee** [comment]
@miriamkos I included the changes to DR and deployed it to the acceptance.  see https://data-acc.donders.ru.nl/doc/help/quickstart.html

But I don't think it is in a state that we could push out to the the DR production because there are still RDR-specific text. Will you update it, @miriamkos?

**Comment by miriamkos** [comment]
> 
> 
> @miriamkos I included the changes to DR and deployed it to the acceptance. see https://data-acc.donders.ru.nl/doc/help/quickstart.html
> 
> But I don't think it is in a state that we could push out to the the DR production because there are still RDR-specific text. Will you update it, @miriamkos?

But this only concerns step 2 and referral to RDR right or am I missing something? I would propose to include the DI information already on the level of the RDR @stijndelaat, do you agree? Referral to RDR could perhaps be used by using a variable? Else I propose to leave it there.

**Comment by hurngchunlee** [comment]
@miriamkos yes, you are right.

**Comment by stijndelaat** [comment]
@miriamkos That is a good idea. Do you have a link to a specific page that I can put under the name? Also, how would you like to be mentioned on the RDR page under step 2? Donders Institute for Brain, Cognition and Behaviour? Or Donders Institute?

**Comment by stijndelaat** [comment]
@hurngchunlee and @miriamkos By the way, I am also working on putting variables on (among others) the quickstart page. Once we have a variable for the abreviation, I shall update the quickstart guide.

**Comment by miriamkos** [comment]
Donders Institute is fine. It would be like this: Donders Institute, Donders Centre for Cognition carrying a hyperlink to https://intranet.donders.ru.nl/index.php?id=5073, Donders Centre for Cognitive Neuroimaging carrying a hyperlink to https://intranet.donders.ru.nl/index.php?id=datastorage-archiving-sharing and Donders Centre for Neuroscience carrying a hyperlink to https://intranet.donders.ru.nl/index.php?id=5511. Thanks!

**Comment by stijndelaat** [comment]
@hurngchunlee. @miriamkos and I have decided that point two under the quickstart guide will be tailored to the DR specific. I have e-mailed Miriam the correct text that could be inserted there. Is that the update you required? If not, just let me know :)

**Comment by hurngchunlee** [comment]
> @hurngchunlee. @miriamkos and I have decided that point two under the quickstart guide will be tailored to the DR specific. I have e-mailed Miriam the correct text that could be inserted there. Is that the update you required? If not, just let me know :)

@stijndelaat concerning the content, I leave the decision to @miriamkos .  I suppose there will be another pull request or commit for me to cherry-pick or merge, right?

**Comment by stijndelaat** [comment]
> 
> @stijndelaat concerning the content, I leave the decision to @miriamkos . I suppose there will be another pull request or commit for me to cherry-pick or merge, right?

I think so. @miriamkos Am I right when I say that you and/or Pauline will add the DR specific text under point two in the quickstart guide and make a pull request/commit?

**Comment by miriamkos** [comment]
@hurngchunlee would you be available to put the text of step 2 in the DR environment...it has been a while that I made adjustments to the documentation and I have not much time now to dig into it...Text should be as follows: Donders Centre for Cognition carrying a hyperlink to https://intranet.donders.ru.nl/index.php?id=5073, Donders Centre for Cognitive Neuroimaging carrying a hyperlink to https://intranet.donders.ru.nl/index.php?id=datastorage-archiving-sharing and Donders Centre for Neuroscience carrying a hyperlink to https://intranet.donders.ru.nl/index.php?id=5511

**Comment by hurngchunlee** [comment]
@miriamkos is it ok like this: https://data-acc.donders.ru.nl/doc/help/quickstart.html
@stijndelaat if my change is approved by @miriamkos, @paulspeijers can cherry-pick this commit: a9826f2384b5068a54dc54d5e8937b6df9a7f812 to RDR branches.

**Comment by stijndelaat** [comment]
> 
> 
> @miriamkos is it ok like this: https://data-acc.donders.ru.nl/doc/help/quickstart.html
> @stijndelaat if my change is approved by @miriamkos, @paulspeijers can cherry-pick this commit: [a9826f2](https://github.com/Radboud-University/rdr-configurable-content/commit/a9826f2384b5068a54dc54d5e8937b6df9a7f812) to RDR branches.

@hurngchunlee and @paulspeijers we do not need this commit in our RDR branches. No need for cherry-picking 😄

**Comment by miriamkos** [comment]
Yes, thanks!

**Pull request merged**
